/* oxlint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as userRouteRouteImport } from './routes/(user)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as adminAdminRouteRouteImport } from './routes/(admin)/admin/route'
import { Route as userWelcomeIndexRouteImport } from './routes/(user)/welcome/index'
import { Route as userDashboardIndexRouteImport } from './routes/(user)/dashboard/index'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as ApiSubTokenRouteImport } from './routes/api/sub/$token'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth/signup'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth/login'
import { Route as authAuthForgotRouteImport } from './routes/(auth)/auth/forgot'
import { Route as adminAdminUsersRouteRouteImport } from './routes/(admin)/admin/users/route'
import { Route as adminAdminProxiesRouteRouteImport } from './routes/(admin)/admin/proxies/route'
import { Route as adminAdminPlansRouteRouteImport } from './routes/(admin)/admin/plans/route'
import { Route as adminAdminUsersIndexRouteImport } from './routes/(admin)/admin/users/index'
import { Route as adminAdminPlansIndexRouteImport } from './routes/(admin)/admin/plans/index'
import { Route as adminAdminUsersUserIdRouteImport } from './routes/(admin)/admin/users/$userId'
import { Route as adminAdminPlansNewRouteImport } from './routes/(admin)/admin/plans/new'
import { Route as adminAdminPlansPlanIdRouteImport } from './routes/(admin)/admin/plans/$planId'
import { Route as adminAdminProxiesNodesRouteRouteImport } from './routes/(admin)/admin/proxies/nodes/route'
import { Route as adminAdminProxiesGroupsRouteRouteImport } from './routes/(admin)/admin/proxies/groups/route'
import { Route as adminAdminProxiesRulesIndexRouteImport } from './routes/(admin)/admin/proxies/rules/index'
import { Route as adminAdminProxiesNodesIndexRouteImport } from './routes/(admin)/admin/proxies/nodes/index'
import { Route as adminAdminProxiesGroupsIndexRouteImport } from './routes/(admin)/admin/proxies/groups/index'
import { Route as adminAdminProxiesNodesNewRouteImport } from './routes/(admin)/admin/proxies/nodes/new'
import { Route as adminAdminProxiesNodesNodeIdRouteImport } from './routes/(admin)/admin/proxies/nodes/$nodeId'
import { Route as adminAdminProxiesGroupsNewRouteImport } from './routes/(admin)/admin/proxies/groups/new'
import { Route as adminAdminProxiesGroupsGroupIdRouteImport } from './routes/(admin)/admin/proxies/groups/$groupId'

const userRouteRoute = userRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const staticIndexRoute = staticIndexRouteImport.update({
  id: '/(static)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRouteRoute = adminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => adminRouteRoute,
} as any)
const userWelcomeIndexRoute = userWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => userRouteRoute,
} as any)
const userDashboardIndexRoute = userDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => userRouteRoute,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminRouteRoute,
} as any)
const ApiSubTokenRoute = ApiSubTokenRouteImport.update({
  id: '/api/sub/$token',
  path: '/api/sub/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthForgotRoute = authAuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => authRouteRoute,
} as any)
const adminAdminUsersRouteRoute = adminAdminUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => adminAdminRouteRoute,
} as any)
const adminAdminProxiesRouteRoute = adminAdminProxiesRouteRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => adminAdminRouteRoute,
} as any)
const adminAdminPlansRouteRoute = adminAdminPlansRouteRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => adminAdminRouteRoute,
} as any)
const adminAdminUsersIndexRoute = adminAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminUsersRouteRoute,
} as any)
const adminAdminPlansIndexRoute = adminAdminPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminPlansRouteRoute,
} as any)
const adminAdminUsersUserIdRoute = adminAdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => adminAdminUsersRouteRoute,
} as any)
const adminAdminPlansNewRoute = adminAdminPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => adminAdminPlansRouteRoute,
} as any)
const adminAdminPlansPlanIdRoute = adminAdminPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => adminAdminPlansRouteRoute,
} as any)
const adminAdminProxiesNodesRouteRoute =
  adminAdminProxiesNodesRouteRouteImport.update({
    id: '/nodes',
    path: '/nodes',
    getParentRoute: () => adminAdminProxiesRouteRoute,
  } as any)
const adminAdminProxiesGroupsRouteRoute =
  adminAdminProxiesGroupsRouteRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => adminAdminProxiesRouteRoute,
  } as any)
const adminAdminProxiesRulesIndexRoute =
  adminAdminProxiesRulesIndexRouteImport.update({
    id: '/rules/',
    path: '/rules/',
    getParentRoute: () => adminAdminProxiesRouteRoute,
  } as any)
const adminAdminProxiesNodesIndexRoute =
  adminAdminProxiesNodesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminProxiesNodesRouteRoute,
  } as any)
const adminAdminProxiesGroupsIndexRoute =
  adminAdminProxiesGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminProxiesGroupsRouteRoute,
  } as any)
const adminAdminProxiesNodesNewRoute =
  adminAdminProxiesNodesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => adminAdminProxiesNodesRouteRoute,
  } as any)
const adminAdminProxiesNodesNodeIdRoute =
  adminAdminProxiesNodesNodeIdRouteImport.update({
    id: '/$nodeId',
    path: '/$nodeId',
    getParentRoute: () => adminAdminProxiesNodesRouteRoute,
  } as any)
const adminAdminProxiesGroupsNewRoute =
  adminAdminProxiesGroupsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => adminAdminProxiesGroupsRouteRoute,
  } as any)
const adminAdminProxiesGroupsGroupIdRoute =
  adminAdminProxiesGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => adminAdminProxiesGroupsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof adminAdminRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof staticIndexRoute
  '/admin/plans': typeof adminAdminPlansRouteRouteWithChildren
  '/admin/proxies': typeof adminAdminProxiesRouteRouteWithChildren
  '/admin/users': typeof adminAdminUsersRouteRouteWithChildren
  '/auth/forgot': typeof authAuthForgotRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sub/$token': typeof ApiSubTokenRoute
  '/admin/': typeof adminAdminIndexRoute
  '/dashboard/': typeof userDashboardIndexRoute
  '/welcome/': typeof userWelcomeIndexRoute
  '/admin/proxies/groups': typeof adminAdminProxiesGroupsRouteRouteWithChildren
  '/admin/proxies/nodes': typeof adminAdminProxiesNodesRouteRouteWithChildren
  '/admin/plans/$planId': typeof adminAdminPlansPlanIdRoute
  '/admin/plans/new': typeof adminAdminPlansNewRoute
  '/admin/users/$userId': typeof adminAdminUsersUserIdRoute
  '/admin/plans/': typeof adminAdminPlansIndexRoute
  '/admin/users/': typeof adminAdminUsersIndexRoute
  '/admin/proxies/groups/$groupId': typeof adminAdminProxiesGroupsGroupIdRoute
  '/admin/proxies/groups/new': typeof adminAdminProxiesGroupsNewRoute
  '/admin/proxies/nodes/$nodeId': typeof adminAdminProxiesNodesNodeIdRoute
  '/admin/proxies/nodes/new': typeof adminAdminProxiesNodesNewRoute
  '/admin/proxies/groups/': typeof adminAdminProxiesGroupsIndexRoute
  '/admin/proxies/nodes/': typeof adminAdminProxiesNodesIndexRoute
  '/admin/proxies/rules/': typeof adminAdminProxiesRulesIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof staticIndexRoute
  '/admin/proxies': typeof adminAdminProxiesRouteRouteWithChildren
  '/auth/forgot': typeof authAuthForgotRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sub/$token': typeof ApiSubTokenRoute
  '/admin': typeof adminAdminIndexRoute
  '/dashboard': typeof userDashboardIndexRoute
  '/welcome': typeof userWelcomeIndexRoute
  '/admin/plans/$planId': typeof adminAdminPlansPlanIdRoute
  '/admin/plans/new': typeof adminAdminPlansNewRoute
  '/admin/users/$userId': typeof adminAdminUsersUserIdRoute
  '/admin/plans': typeof adminAdminPlansIndexRoute
  '/admin/users': typeof adminAdminUsersIndexRoute
  '/admin/proxies/groups/$groupId': typeof adminAdminProxiesGroupsGroupIdRoute
  '/admin/proxies/groups/new': typeof adminAdminProxiesGroupsNewRoute
  '/admin/proxies/nodes/$nodeId': typeof adminAdminProxiesNodesNodeIdRoute
  '/admin/proxies/nodes/new': typeof adminAdminProxiesNodesNewRoute
  '/admin/proxies/groups': typeof adminAdminProxiesGroupsIndexRoute
  '/admin/proxies/nodes': typeof adminAdminProxiesNodesIndexRoute
  '/admin/proxies/rules': typeof adminAdminProxiesRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/(admin)/admin': typeof adminAdminRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/(static)/': typeof staticIndexRoute
  '/(admin)/admin/plans': typeof adminAdminPlansRouteRouteWithChildren
  '/(admin)/admin/proxies': typeof adminAdminProxiesRouteRouteWithChildren
  '/(admin)/admin/users': typeof adminAdminUsersRouteRouteWithChildren
  '/(auth)/auth/forgot': typeof authAuthForgotRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/sub/$token': typeof ApiSubTokenRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(user)/dashboard/': typeof userDashboardIndexRoute
  '/(user)/welcome/': typeof userWelcomeIndexRoute
  '/(admin)/admin/proxies/groups': typeof adminAdminProxiesGroupsRouteRouteWithChildren
  '/(admin)/admin/proxies/nodes': typeof adminAdminProxiesNodesRouteRouteWithChildren
  '/(admin)/admin/plans/$planId': typeof adminAdminPlansPlanIdRoute
  '/(admin)/admin/plans/new': typeof adminAdminPlansNewRoute
  '/(admin)/admin/users/$userId': typeof adminAdminUsersUserIdRoute
  '/(admin)/admin/plans/': typeof adminAdminPlansIndexRoute
  '/(admin)/admin/users/': typeof adminAdminUsersIndexRoute
  '/(admin)/admin/proxies/groups/$groupId': typeof adminAdminProxiesGroupsGroupIdRoute
  '/(admin)/admin/proxies/groups/new': typeof adminAdminProxiesGroupsNewRoute
  '/(admin)/admin/proxies/nodes/$nodeId': typeof adminAdminProxiesNodesNodeIdRoute
  '/(admin)/admin/proxies/nodes/new': typeof adminAdminProxiesNodesNewRoute
  '/(admin)/admin/proxies/groups/': typeof adminAdminProxiesGroupsIndexRoute
  '/(admin)/admin/proxies/nodes/': typeof adminAdminProxiesNodesIndexRoute
  '/(admin)/admin/proxies/rules/': typeof adminAdminProxiesRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/api/$'
    | '/api/health'
    | '/'
    | '/admin/plans'
    | '/admin/proxies'
    | '/admin/users'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/sub/$token'
    | '/admin/'
    | '/dashboard/'
    | '/welcome/'
    | '/admin/proxies/groups'
    | '/admin/proxies/nodes'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/admin/users/$userId'
    | '/admin/plans/'
    | '/admin/users/'
    | '/admin/proxies/groups/$groupId'
    | '/admin/proxies/groups/new'
    | '/admin/proxies/nodes/$nodeId'
    | '/admin/proxies/nodes/new'
    | '/admin/proxies/groups/'
    | '/admin/proxies/nodes/'
    | '/admin/proxies/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/api/health'
    | '/'
    | '/admin/proxies'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/sub/$token'
    | '/admin'
    | '/dashboard'
    | '/welcome'
    | '/admin/plans/$planId'
    | '/admin/plans/new'
    | '/admin/users/$userId'
    | '/admin/plans'
    | '/admin/users'
    | '/admin/proxies/groups/$groupId'
    | '/admin/proxies/groups/new'
    | '/admin/proxies/nodes/$nodeId'
    | '/admin/proxies/nodes/new'
    | '/admin/proxies/groups'
    | '/admin/proxies/nodes'
    | '/admin/proxies/rules'
  id:
    | '__root__'
    | '/(admin)'
    | '/(auth)'
    | '/(user)'
    | '/(admin)/admin'
    | '/api/$'
    | '/api/health'
    | '/(static)/'
    | '/(admin)/admin/plans'
    | '/(admin)/admin/proxies'
    | '/(admin)/admin/users'
    | '/(auth)/auth/forgot'
    | '/(auth)/auth/login'
    | '/(auth)/auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/sub/$token'
    | '/(admin)/admin/'
    | '/(user)/dashboard/'
    | '/(user)/welcome/'
    | '/(admin)/admin/proxies/groups'
    | '/(admin)/admin/proxies/nodes'
    | '/(admin)/admin/plans/$planId'
    | '/(admin)/admin/plans/new'
    | '/(admin)/admin/users/$userId'
    | '/(admin)/admin/plans/'
    | '/(admin)/admin/users/'
    | '/(admin)/admin/proxies/groups/$groupId'
    | '/(admin)/admin/proxies/groups/new'
    | '/(admin)/admin/proxies/nodes/$nodeId'
    | '/(admin)/admin/proxies/nodes/new'
    | '/(admin)/admin/proxies/groups/'
    | '/(admin)/admin/proxies/nodes/'
    | '/(admin)/admin/proxies/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  staticIndexRoute: typeof staticIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiSubTokenRoute: typeof ApiSubTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(user)': {
      id: '/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof userRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin': {
      id: '/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(user)/welcome/': {
      id: '/(user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof userWelcomeIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/dashboard/': {
      id: '/(user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof userDashboardIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminAdminRouteRoute
    }
    '/api/sub/$token': {
      id: '/api/sub/$token'
      path: '/api/sub/$token'
      fullPath: '/api/sub/$token'
      preLoaderRoute: typeof ApiSubTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/forgot': {
      id: '/(auth)/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof authAuthForgotRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(admin)/admin/users': {
      id: '/(admin)/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminAdminUsersRouteRouteImport
      parentRoute: typeof adminAdminRouteRoute
    }
    '/(admin)/admin/proxies': {
      id: '/(admin)/admin/proxies'
      path: '/proxies'
      fullPath: '/admin/proxies'
      preLoaderRoute: typeof adminAdminProxiesRouteRouteImport
      parentRoute: typeof adminAdminRouteRoute
    }
    '/(admin)/admin/plans': {
      id: '/(admin)/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof adminAdminPlansRouteRouteImport
      parentRoute: typeof adminAdminRouteRoute
    }
    '/(admin)/admin/users/': {
      id: '/(admin)/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof adminAdminUsersIndexRouteImport
      parentRoute: typeof adminAdminUsersRouteRoute
    }
    '/(admin)/admin/plans/': {
      id: '/(admin)/admin/plans/'
      path: '/'
      fullPath: '/admin/plans/'
      preLoaderRoute: typeof adminAdminPlansIndexRouteImport
      parentRoute: typeof adminAdminPlansRouteRoute
    }
    '/(admin)/admin/users/$userId': {
      id: '/(admin)/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof adminAdminUsersUserIdRouteImport
      parentRoute: typeof adminAdminUsersRouteRoute
    }
    '/(admin)/admin/plans/new': {
      id: '/(admin)/admin/plans/new'
      path: '/new'
      fullPath: '/admin/plans/new'
      preLoaderRoute: typeof adminAdminPlansNewRouteImport
      parentRoute: typeof adminAdminPlansRouteRoute
    }
    '/(admin)/admin/plans/$planId': {
      id: '/(admin)/admin/plans/$planId'
      path: '/$planId'
      fullPath: '/admin/plans/$planId'
      preLoaderRoute: typeof adminAdminPlansPlanIdRouteImport
      parentRoute: typeof adminAdminPlansRouteRoute
    }
    '/(admin)/admin/proxies/nodes': {
      id: '/(admin)/admin/proxies/nodes'
      path: '/nodes'
      fullPath: '/admin/proxies/nodes'
      preLoaderRoute: typeof adminAdminProxiesNodesRouteRouteImport
      parentRoute: typeof adminAdminProxiesRouteRoute
    }
    '/(admin)/admin/proxies/groups': {
      id: '/(admin)/admin/proxies/groups'
      path: '/groups'
      fullPath: '/admin/proxies/groups'
      preLoaderRoute: typeof adminAdminProxiesGroupsRouteRouteImport
      parentRoute: typeof adminAdminProxiesRouteRoute
    }
    '/(admin)/admin/proxies/rules/': {
      id: '/(admin)/admin/proxies/rules/'
      path: '/rules'
      fullPath: '/admin/proxies/rules/'
      preLoaderRoute: typeof adminAdminProxiesRulesIndexRouteImport
      parentRoute: typeof adminAdminProxiesRouteRoute
    }
    '/(admin)/admin/proxies/nodes/': {
      id: '/(admin)/admin/proxies/nodes/'
      path: '/'
      fullPath: '/admin/proxies/nodes/'
      preLoaderRoute: typeof adminAdminProxiesNodesIndexRouteImport
      parentRoute: typeof adminAdminProxiesNodesRouteRoute
    }
    '/(admin)/admin/proxies/groups/': {
      id: '/(admin)/admin/proxies/groups/'
      path: '/'
      fullPath: '/admin/proxies/groups/'
      preLoaderRoute: typeof adminAdminProxiesGroupsIndexRouteImport
      parentRoute: typeof adminAdminProxiesGroupsRouteRoute
    }
    '/(admin)/admin/proxies/nodes/new': {
      id: '/(admin)/admin/proxies/nodes/new'
      path: '/new'
      fullPath: '/admin/proxies/nodes/new'
      preLoaderRoute: typeof adminAdminProxiesNodesNewRouteImport
      parentRoute: typeof adminAdminProxiesNodesRouteRoute
    }
    '/(admin)/admin/proxies/nodes/$nodeId': {
      id: '/(admin)/admin/proxies/nodes/$nodeId'
      path: '/$nodeId'
      fullPath: '/admin/proxies/nodes/$nodeId'
      preLoaderRoute: typeof adminAdminProxiesNodesNodeIdRouteImport
      parentRoute: typeof adminAdminProxiesNodesRouteRoute
    }
    '/(admin)/admin/proxies/groups/new': {
      id: '/(admin)/admin/proxies/groups/new'
      path: '/new'
      fullPath: '/admin/proxies/groups/new'
      preLoaderRoute: typeof adminAdminProxiesGroupsNewRouteImport
      parentRoute: typeof adminAdminProxiesGroupsRouteRoute
    }
    '/(admin)/admin/proxies/groups/$groupId': {
      id: '/(admin)/admin/proxies/groups/$groupId'
      path: '/$groupId'
      fullPath: '/admin/proxies/groups/$groupId'
      preLoaderRoute: typeof adminAdminProxiesGroupsGroupIdRouteImport
      parentRoute: typeof adminAdminProxiesGroupsRouteRoute
    }
  }
}

interface adminAdminPlansRouteRouteChildren {
  adminAdminPlansPlanIdRoute: typeof adminAdminPlansPlanIdRoute
  adminAdminPlansNewRoute: typeof adminAdminPlansNewRoute
  adminAdminPlansIndexRoute: typeof adminAdminPlansIndexRoute
}

const adminAdminPlansRouteRouteChildren: adminAdminPlansRouteRouteChildren = {
  adminAdminPlansPlanIdRoute: adminAdminPlansPlanIdRoute,
  adminAdminPlansNewRoute: adminAdminPlansNewRoute,
  adminAdminPlansIndexRoute: adminAdminPlansIndexRoute,
}

const adminAdminPlansRouteRouteWithChildren =
  adminAdminPlansRouteRoute._addFileChildren(adminAdminPlansRouteRouteChildren)

interface adminAdminProxiesGroupsRouteRouteChildren {
  adminAdminProxiesGroupsGroupIdRoute: typeof adminAdminProxiesGroupsGroupIdRoute
  adminAdminProxiesGroupsNewRoute: typeof adminAdminProxiesGroupsNewRoute
  adminAdminProxiesGroupsIndexRoute: typeof adminAdminProxiesGroupsIndexRoute
}

const adminAdminProxiesGroupsRouteRouteChildren: adminAdminProxiesGroupsRouteRouteChildren =
  {
    adminAdminProxiesGroupsGroupIdRoute: adminAdminProxiesGroupsGroupIdRoute,
    adminAdminProxiesGroupsNewRoute: adminAdminProxiesGroupsNewRoute,
    adminAdminProxiesGroupsIndexRoute: adminAdminProxiesGroupsIndexRoute,
  }

const adminAdminProxiesGroupsRouteRouteWithChildren =
  adminAdminProxiesGroupsRouteRoute._addFileChildren(
    adminAdminProxiesGroupsRouteRouteChildren,
  )

interface adminAdminProxiesNodesRouteRouteChildren {
  adminAdminProxiesNodesNodeIdRoute: typeof adminAdminProxiesNodesNodeIdRoute
  adminAdminProxiesNodesNewRoute: typeof adminAdminProxiesNodesNewRoute
  adminAdminProxiesNodesIndexRoute: typeof adminAdminProxiesNodesIndexRoute
}

const adminAdminProxiesNodesRouteRouteChildren: adminAdminProxiesNodesRouteRouteChildren =
  {
    adminAdminProxiesNodesNodeIdRoute: adminAdminProxiesNodesNodeIdRoute,
    adminAdminProxiesNodesNewRoute: adminAdminProxiesNodesNewRoute,
    adminAdminProxiesNodesIndexRoute: adminAdminProxiesNodesIndexRoute,
  }

const adminAdminProxiesNodesRouteRouteWithChildren =
  adminAdminProxiesNodesRouteRoute._addFileChildren(
    adminAdminProxiesNodesRouteRouteChildren,
  )

interface adminAdminProxiesRouteRouteChildren {
  adminAdminProxiesGroupsRouteRoute: typeof adminAdminProxiesGroupsRouteRouteWithChildren
  adminAdminProxiesNodesRouteRoute: typeof adminAdminProxiesNodesRouteRouteWithChildren
  adminAdminProxiesRulesIndexRoute: typeof adminAdminProxiesRulesIndexRoute
}

const adminAdminProxiesRouteRouteChildren: adminAdminProxiesRouteRouteChildren =
  {
    adminAdminProxiesGroupsRouteRoute:
      adminAdminProxiesGroupsRouteRouteWithChildren,
    adminAdminProxiesNodesRouteRoute:
      adminAdminProxiesNodesRouteRouteWithChildren,
    adminAdminProxiesRulesIndexRoute: adminAdminProxiesRulesIndexRoute,
  }

const adminAdminProxiesRouteRouteWithChildren =
  adminAdminProxiesRouteRoute._addFileChildren(
    adminAdminProxiesRouteRouteChildren,
  )

interface adminAdminUsersRouteRouteChildren {
  adminAdminUsersUserIdRoute: typeof adminAdminUsersUserIdRoute
  adminAdminUsersIndexRoute: typeof adminAdminUsersIndexRoute
}

const adminAdminUsersRouteRouteChildren: adminAdminUsersRouteRouteChildren = {
  adminAdminUsersUserIdRoute: adminAdminUsersUserIdRoute,
  adminAdminUsersIndexRoute: adminAdminUsersIndexRoute,
}

const adminAdminUsersRouteRouteWithChildren =
  adminAdminUsersRouteRoute._addFileChildren(adminAdminUsersRouteRouteChildren)

interface adminAdminRouteRouteChildren {
  adminAdminPlansRouteRoute: typeof adminAdminPlansRouteRouteWithChildren
  adminAdminProxiesRouteRoute: typeof adminAdminProxiesRouteRouteWithChildren
  adminAdminUsersRouteRoute: typeof adminAdminUsersRouteRouteWithChildren
  adminAdminIndexRoute: typeof adminAdminIndexRoute
}

const adminAdminRouteRouteChildren: adminAdminRouteRouteChildren = {
  adminAdminPlansRouteRoute: adminAdminPlansRouteRouteWithChildren,
  adminAdminProxiesRouteRoute: adminAdminProxiesRouteRouteWithChildren,
  adminAdminUsersRouteRoute: adminAdminUsersRouteRouteWithChildren,
  adminAdminIndexRoute: adminAdminIndexRoute,
}

const adminAdminRouteRouteWithChildren = adminAdminRouteRoute._addFileChildren(
  adminAdminRouteRouteChildren,
)

interface adminRouteRouteChildren {
  adminAdminRouteRoute: typeof adminAdminRouteRouteWithChildren
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminRouteRoute: adminAdminRouteRouteWithChildren,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAuthForgotRoute: typeof authAuthForgotRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthForgotRoute: authAuthForgotRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface userRouteRouteChildren {
  userDashboardIndexRoute: typeof userDashboardIndexRoute
  userWelcomeIndexRoute: typeof userWelcomeIndexRoute
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userDashboardIndexRoute: userDashboardIndexRoute,
  userWelcomeIndexRoute: userWelcomeIndexRoute,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  staticIndexRoute: staticIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiSubTokenRoute: ApiSubTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
