/* oxlint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as userRouteRouteImport } from './routes/(user)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as staticIndexRouteImport } from './routes/(static)/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as adminAdminRouteRouteImport } from './routes/(admin)/admin/route'
import { Route as userWelcomeIndexRouteImport } from './routes/(user)/welcome/index'
import { Route as userDashboardIndexRouteImport } from './routes/(user)/dashboard/index'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as authAuthSignupRouteImport } from './routes/(auth)/auth/signup'
import { Route as authAuthLoginRouteImport } from './routes/(auth)/auth/login'
import { Route as authAuthForgotRouteImport } from './routes/(auth)/auth/forgot'
import { Route as adminAdminProxiesRouteRouteImport } from './routes/(admin)/admin/proxies/route'
import { Route as adminAdminProxiesNodesRouteRouteImport } from './routes/(admin)/admin/proxies/nodes/route'
import { Route as adminAdminProxiesRulesIndexRouteImport } from './routes/(admin)/admin/proxies/rules/index'
import { Route as adminAdminProxiesNodesIndexRouteImport } from './routes/(admin)/admin/proxies/nodes/index'
import { Route as adminAdminProxiesGroupsIndexRouteImport } from './routes/(admin)/admin/proxies/groups/index'
import { Route as adminAdminProxiesNodesNewRouteImport } from './routes/(admin)/admin/proxies/nodes/new'
import { Route as adminAdminProxiesNodesNodeIdRouteImport } from './routes/(admin)/admin/proxies/nodes/$nodeId'

const userRouteRoute = userRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const staticIndexRoute = staticIndexRouteImport.update({
  id: '/(static)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const adminAdminRouteRoute = adminAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => adminRouteRoute,
} as any)
const userWelcomeIndexRoute = userWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => userRouteRoute,
} as any)
const userDashboardIndexRoute = userDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => userRouteRoute,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => adminAdminRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignupRoute = authAuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthLoginRoute = authAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authAuthForgotRoute = authAuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => authRouteRoute,
} as any)
const adminAdminProxiesRouteRoute = adminAdminProxiesRouteRouteImport.update({
  id: '/proxies',
  path: '/proxies',
  getParentRoute: () => adminAdminRouteRoute,
} as any)
const adminAdminProxiesNodesRouteRoute =
  adminAdminProxiesNodesRouteRouteImport.update({
    id: '/nodes',
    path: '/nodes',
    getParentRoute: () => adminAdminProxiesRouteRoute,
  } as any)
const adminAdminProxiesRulesIndexRoute =
  adminAdminProxiesRulesIndexRouteImport.update({
    id: '/rules/',
    path: '/rules/',
    getParentRoute: () => adminAdminProxiesRouteRoute,
  } as any)
const adminAdminProxiesNodesIndexRoute =
  adminAdminProxiesNodesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => adminAdminProxiesNodesRouteRoute,
  } as any)
const adminAdminProxiesGroupsIndexRoute =
  adminAdminProxiesGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => adminAdminProxiesRouteRoute,
  } as any)
const adminAdminProxiesNodesNewRoute =
  adminAdminProxiesNodesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => adminAdminProxiesNodesRouteRoute,
  } as any)
const adminAdminProxiesNodesNodeIdRoute =
  adminAdminProxiesNodesNodeIdRouteImport.update({
    id: '/$nodeId',
    path: '/$nodeId',
    getParentRoute: () => adminAdminProxiesNodesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof adminAdminRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/': typeof staticIndexRoute
  '/admin/proxies': typeof adminAdminProxiesRouteRouteWithChildren
  '/auth/forgot': typeof authAuthForgotRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/': typeof adminAdminIndexRoute
  '/dashboard/': typeof userDashboardIndexRoute
  '/welcome/': typeof userWelcomeIndexRoute
  '/admin/proxies/nodes': typeof adminAdminProxiesNodesRouteRouteWithChildren
  '/admin/proxies/nodes/$nodeId': typeof adminAdminProxiesNodesNodeIdRoute
  '/admin/proxies/nodes/new': typeof adminAdminProxiesNodesNewRoute
  '/admin/proxies/groups/': typeof adminAdminProxiesGroupsIndexRoute
  '/admin/proxies/nodes/': typeof adminAdminProxiesNodesIndexRoute
  '/admin/proxies/rules/': typeof adminAdminProxiesRulesIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/': typeof staticIndexRoute
  '/admin/proxies': typeof adminAdminProxiesRouteRouteWithChildren
  '/auth/forgot': typeof authAuthForgotRoute
  '/auth/login': typeof authAuthLoginRoute
  '/auth/signup': typeof authAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin': typeof adminAdminIndexRoute
  '/dashboard': typeof userDashboardIndexRoute
  '/welcome': typeof userWelcomeIndexRoute
  '/admin/proxies/nodes/$nodeId': typeof adminAdminProxiesNodesNodeIdRoute
  '/admin/proxies/nodes/new': typeof adminAdminProxiesNodesNewRoute
  '/admin/proxies/groups': typeof adminAdminProxiesGroupsIndexRoute
  '/admin/proxies/nodes': typeof adminAdminProxiesNodesIndexRoute
  '/admin/proxies/rules': typeof adminAdminProxiesRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/(admin)/admin': typeof adminAdminRouteRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/(static)/': typeof staticIndexRoute
  '/(admin)/admin/proxies': typeof adminAdminProxiesRouteRouteWithChildren
  '/(auth)/auth/forgot': typeof authAuthForgotRoute
  '/(auth)/auth/login': typeof authAuthLoginRoute
  '/(auth)/auth/signup': typeof authAuthSignupRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(user)/dashboard/': typeof userDashboardIndexRoute
  '/(user)/welcome/': typeof userWelcomeIndexRoute
  '/(admin)/admin/proxies/nodes': typeof adminAdminProxiesNodesRouteRouteWithChildren
  '/(admin)/admin/proxies/nodes/$nodeId': typeof adminAdminProxiesNodesNodeIdRoute
  '/(admin)/admin/proxies/nodes/new': typeof adminAdminProxiesNodesNewRoute
  '/(admin)/admin/proxies/groups/': typeof adminAdminProxiesGroupsIndexRoute
  '/(admin)/admin/proxies/nodes/': typeof adminAdminProxiesNodesIndexRoute
  '/(admin)/admin/proxies/rules/': typeof adminAdminProxiesRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/api/$'
    | '/'
    | '/admin/proxies'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin/'
    | '/dashboard/'
    | '/welcome/'
    | '/admin/proxies/nodes'
    | '/admin/proxies/nodes/$nodeId'
    | '/admin/proxies/nodes/new'
    | '/admin/proxies/groups/'
    | '/admin/proxies/nodes/'
    | '/admin/proxies/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/$'
    | '/'
    | '/admin/proxies'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/admin'
    | '/dashboard'
    | '/welcome'
    | '/admin/proxies/nodes/$nodeId'
    | '/admin/proxies/nodes/new'
    | '/admin/proxies/groups'
    | '/admin/proxies/nodes'
    | '/admin/proxies/rules'
  id:
    | '__root__'
    | '/(admin)'
    | '/(auth)'
    | '/(user)'
    | '/(admin)/admin'
    | '/api/$'
    | '/(static)/'
    | '/(admin)/admin/proxies'
    | '/(auth)/auth/forgot'
    | '/(auth)/auth/login'
    | '/(auth)/auth/signup'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/(admin)/admin/'
    | '/(user)/dashboard/'
    | '/(user)/welcome/'
    | '/(admin)/admin/proxies/nodes'
    | '/(admin)/admin/proxies/nodes/$nodeId'
    | '/(admin)/admin/proxies/nodes/new'
    | '/(admin)/admin/proxies/groups/'
    | '/(admin)/admin/proxies/nodes/'
    | '/(admin)/admin/proxies/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  staticIndexRoute: typeof staticIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(user)': {
      id: '/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof userRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(static)/': {
      id: '/(static)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof staticIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/admin': {
      id: '/(admin)/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof adminAdminRouteRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(user)/welcome/': {
      id: '/(user)/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof userWelcomeIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/dashboard/': {
      id: '/(user)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof userDashboardIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminAdminRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/signup': {
      id: '/(auth)/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof authAuthSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/login': {
      id: '/(auth)/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof authAuthLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/auth/forgot': {
      id: '/(auth)/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof authAuthForgotRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(admin)/admin/proxies': {
      id: '/(admin)/admin/proxies'
      path: '/proxies'
      fullPath: '/admin/proxies'
      preLoaderRoute: typeof adminAdminProxiesRouteRouteImport
      parentRoute: typeof adminAdminRouteRoute
    }
    '/(admin)/admin/proxies/nodes': {
      id: '/(admin)/admin/proxies/nodes'
      path: '/nodes'
      fullPath: '/admin/proxies/nodes'
      preLoaderRoute: typeof adminAdminProxiesNodesRouteRouteImport
      parentRoute: typeof adminAdminProxiesRouteRoute
    }
    '/(admin)/admin/proxies/rules/': {
      id: '/(admin)/admin/proxies/rules/'
      path: '/rules'
      fullPath: '/admin/proxies/rules/'
      preLoaderRoute: typeof adminAdminProxiesRulesIndexRouteImport
      parentRoute: typeof adminAdminProxiesRouteRoute
    }
    '/(admin)/admin/proxies/nodes/': {
      id: '/(admin)/admin/proxies/nodes/'
      path: '/'
      fullPath: '/admin/proxies/nodes/'
      preLoaderRoute: typeof adminAdminProxiesNodesIndexRouteImport
      parentRoute: typeof adminAdminProxiesNodesRouteRoute
    }
    '/(admin)/admin/proxies/groups/': {
      id: '/(admin)/admin/proxies/groups/'
      path: '/groups'
      fullPath: '/admin/proxies/groups/'
      preLoaderRoute: typeof adminAdminProxiesGroupsIndexRouteImport
      parentRoute: typeof adminAdminProxiesRouteRoute
    }
    '/(admin)/admin/proxies/nodes/new': {
      id: '/(admin)/admin/proxies/nodes/new'
      path: '/new'
      fullPath: '/admin/proxies/nodes/new'
      preLoaderRoute: typeof adminAdminProxiesNodesNewRouteImport
      parentRoute: typeof adminAdminProxiesNodesRouteRoute
    }
    '/(admin)/admin/proxies/nodes/$nodeId': {
      id: '/(admin)/admin/proxies/nodes/$nodeId'
      path: '/$nodeId'
      fullPath: '/admin/proxies/nodes/$nodeId'
      preLoaderRoute: typeof adminAdminProxiesNodesNodeIdRouteImport
      parentRoute: typeof adminAdminProxiesNodesRouteRoute
    }
  }
}

interface adminAdminProxiesNodesRouteRouteChildren {
  adminAdminProxiesNodesNodeIdRoute: typeof adminAdminProxiesNodesNodeIdRoute
  adminAdminProxiesNodesNewRoute: typeof adminAdminProxiesNodesNewRoute
  adminAdminProxiesNodesIndexRoute: typeof adminAdminProxiesNodesIndexRoute
}

const adminAdminProxiesNodesRouteRouteChildren: adminAdminProxiesNodesRouteRouteChildren =
  {
    adminAdminProxiesNodesNodeIdRoute: adminAdminProxiesNodesNodeIdRoute,
    adminAdminProxiesNodesNewRoute: adminAdminProxiesNodesNewRoute,
    adminAdminProxiesNodesIndexRoute: adminAdminProxiesNodesIndexRoute,
  }

const adminAdminProxiesNodesRouteRouteWithChildren =
  adminAdminProxiesNodesRouteRoute._addFileChildren(
    adminAdminProxiesNodesRouteRouteChildren,
  )

interface adminAdminProxiesRouteRouteChildren {
  adminAdminProxiesNodesRouteRoute: typeof adminAdminProxiesNodesRouteRouteWithChildren
  adminAdminProxiesGroupsIndexRoute: typeof adminAdminProxiesGroupsIndexRoute
  adminAdminProxiesRulesIndexRoute: typeof adminAdminProxiesRulesIndexRoute
}

const adminAdminProxiesRouteRouteChildren: adminAdminProxiesRouteRouteChildren =
  {
    adminAdminProxiesNodesRouteRoute:
      adminAdminProxiesNodesRouteRouteWithChildren,
    adminAdminProxiesGroupsIndexRoute: adminAdminProxiesGroupsIndexRoute,
    adminAdminProxiesRulesIndexRoute: adminAdminProxiesRulesIndexRoute,
  }

const adminAdminProxiesRouteRouteWithChildren =
  adminAdminProxiesRouteRoute._addFileChildren(
    adminAdminProxiesRouteRouteChildren,
  )

interface adminAdminRouteRouteChildren {
  adminAdminProxiesRouteRoute: typeof adminAdminProxiesRouteRouteWithChildren
  adminAdminIndexRoute: typeof adminAdminIndexRoute
}

const adminAdminRouteRouteChildren: adminAdminRouteRouteChildren = {
  adminAdminProxiesRouteRoute: adminAdminProxiesRouteRouteWithChildren,
  adminAdminIndexRoute: adminAdminIndexRoute,
}

const adminAdminRouteRouteWithChildren = adminAdminRouteRoute._addFileChildren(
  adminAdminRouteRouteChildren,
)

interface adminRouteRouteChildren {
  adminAdminRouteRoute: typeof adminAdminRouteRouteWithChildren
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminRouteRoute: adminAdminRouteRouteWithChildren,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authAuthForgotRoute: typeof authAuthForgotRoute
  authAuthLoginRoute: typeof authAuthLoginRoute
  authAuthSignupRoute: typeof authAuthSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authAuthForgotRoute: authAuthForgotRoute,
  authAuthLoginRoute: authAuthLoginRoute,
  authAuthSignupRoute: authAuthSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface userRouteRouteChildren {
  userDashboardIndexRoute: typeof userDashboardIndexRoute
  userWelcomeIndexRoute: typeof userWelcomeIndexRoute
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userDashboardIndexRoute: userDashboardIndexRoute,
  userWelcomeIndexRoute: userWelcomeIndexRoute,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  staticIndexRoute: staticIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
